using BasicLang.Forms;
using BasicLang.Forms.Recognizer;
using NUnit.Framework;
using VisualGameStudio.Core.Abstractions.Services;
using VisualGameStudio.ProjectSystem.Services;

namespace VisualGameStudio.Tests.Compiler;

/// <summary>
/// Task 5: the recognizer, against the three source shapes that actually exist.
///
/// <para>⛔ The fixtures are generated by the REAL template service and read from the REAL VSIX
/// template file, never hand-copied into this fixture. A hand-copied string would keep passing
/// after someone edited the template, which is the precise way this gate could pass by absence:
/// neither shipped IDE template has an <c>InitializeComponent</c>, so a reader written against the
/// VS convention recovers zero controls from both and a suite built on its own strings never
/// notices.</para>
/// </summary>
[TestFixture]
public class FormRecognizerTests
{
    private string _dir = null!;
    private ProjectTemplateService _service = null!;

    [SetUp]
    public void SetUp()
    {
        _service = new ProjectTemplateService();
        _dir = Path.Combine(Path.GetTempPath(), "bl-recognizer-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_dir);
    }

    [TearDown]
    public void TearDown() { try { Directory.Delete(_dir, true); } catch { } }

    private static string? FindRepoFile(params string[] relativeParts)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            var candidate = Path.Combine(new[] { dir.FullName }.Concat(relativeParts).ToArray());
            if (File.Exists(candidate)) return candidate;
            dir = dir.Parent;
        }
        return null;
    }

    /// <summary>Generates a project from a real template and returns the named source file's text.</summary>
    private async Task<string> GenerateAsync(string templateId, SolutionType solutionType, string fileName)
    {
        var result = await _service.CreateProjectAsync(new CreateProjectOptions
        {
            Name = "Recog",
            Location = _dir,
            SolutionType = solutionType,
            Template = ProjectTemplates.All.Single(t => t.Id == templateId),
            CreateSolutionFolder = false,
            CreateGitRepository = false
        });

        Assert.That(result.Success, Is.True, result.Error);
        var path = Path.Combine(Path.GetDirectoryName(result.ProjectPath!)!, fileName);
        Assert.That(File.Exists(path), Is.True, $"the '{templateId}' template did not produce {fileName}");
        return await File.ReadAllTextAsync(path);
    }

    // ==================================================================
    // Fixture 1 — the winforms-app template. Controls live in Public Sub New().
    // ==================================================================

    [Test]
    public async Task WinForms_RecoversTheTemplatesControls_FromAConstructorBody()
    {
        var source = await GenerateAsync("winforms-app", SolutionTypes.DotNet, "Main.bas");

        // The shape this gate exists for: the IDE's own template has no InitializeComponent.
        Assert.That(source, Does.Not.Contain("InitializeComponent"),
            "if the template gained an InitializeComponent, this fixture no longer proves the " +
            "constructor-body path works — add a separate fixture rather than relaxing this");
        Assert.That(source, Does.Contain("Public Sub New()"));

        var form = WinFormsDialect.Read(source);

        Assert.Multiple(() =>
        {
            Assert.That(form.ClassName, Is.EqualTo("MainForm"));
            Assert.That(form.BaseType, Is.EqualTo("Form"));
            Assert.That(form.BuiltIn, Is.EqualTo("New"),
                "the controls are built in the constructor, and the recognizer must say so");
            Assert.That(form.Controls.Select(c => c.Id), Is.EqualTo(new[] { "lblMessage", "btnClick" }),
                "exactly the two controls ProjectTemplateService.GenerateWinFormsMain constructs, in order");
            Assert.That(form.IsRefused, Is.False);
        });

        var label = form["lblMessage"]!;
        Assert.Multiple(() =>
        {
            Assert.That(label.TypeName, Is.EqualTo("Label"));
            Assert.That(label.CatalogKind, Is.EqualTo("Label"));
            Assert.That(label.IsParented, Is.True, "Me.Controls.Add(lblMessage) parents it");
            Assert.That(label.Properties["Text"], Is.EqualTo("\"Hello, Recog!\""),
                "the project name is substituted into the template, and the raw right-hand side is kept");
            Assert.That(label.Properties["Location"], Is.EqualTo("New Point(20, 20)"),
                "an expression the recognizer cannot evaluate must survive verbatim — it is an importer");
            Assert.That(label.Properties["Size"], Is.EqualTo("New Size(300, 30)"));
            Assert.That(label.Properties["Font"], Is.EqualTo("New Font(\"Segoe UI\", 12)"));
            Assert.That(label.Handlers, Is.Empty);
        });

        var button = form["btnClick"]!;
        Assert.Multiple(() =>
        {
            Assert.That(button.TypeName, Is.EqualTo("Button"));
            Assert.That(button.CatalogKind, Is.EqualTo("Button"));
            Assert.That(button.IsParented, Is.True);
            Assert.That(button.Properties["Text"], Is.EqualTo("\"Click Me\""));
            Assert.That(button.Handlers, Has.Count.EqualTo(1));
            Assert.That(button.Handlers[0].Event, Is.EqualTo("Click"));
            Assert.That(button.Handlers[0].Handler, Is.EqualTo("OnButtonClick"));
            Assert.That(button.Handlers[0].IsInline, Is.False);
        });
    }

    [Test]
    public async Task WinForms_RecoversFormLevelProperties_AndNotTheirConstructorNoise()
    {
        var source = await GenerateAsync("winforms-app", SolutionTypes.DotNet, "Main.bas");
        var form = WinFormsDialect.Read(source);

        Assert.Multiple(() =>
        {
            Assert.That(form.FormProperties["Text"], Is.EqualTo("\"Recog\""));
            Assert.That(form.FormProperties["Size"], Is.EqualTo("New Size(400, 300)"));
            Assert.That(form.FormProperties["StartPosition"], Is.EqualTo("FormStartPosition.CenterScreen"));

            // New Size / New Point / New Font all match the `<id> = New <Type>(` shape. None is a
            // control, and a recognizer that took them for controls would show three phantoms.
            Assert.That(form.Controls.Select(c => c.Id),
                Has.No.Member("Size").And.No.Member("Point").And.No.Member("Font"));
        });
    }

    [Test]
    public async Task WinForms_RecoversPositions_NotJustNames()
    {
        var source = await GenerateAsync("winforms-app", SolutionTypes.DotNet, "Main.bas");
        var form = WinFormsDialect.Read(source);

        var lines = source.Replace("\r\n", "\n").Split('\n');
        var label = form["lblMessage"]!;

        Assert.Multiple(() =>
        {
            Assert.That(lines[label.DeclarationLine - 1], Does.Contain("Private lblMessage As Label"),
                "the declaration line must point at the declaration — the writer edits by offset");
            Assert.That(lines[label.ConstructionLine - 1], Does.Contain("lblMessage = New Label()"));
            Assert.That(label.DeclarationLine, Is.LessThan(label.ConstructionLine));
        });
    }

    // ==================================================================
    // Fixture 2 — the web-site template. Elements live in Sub Main().
    // ==================================================================

    [Test]
    public async Task Dom_RecoversTheTemplatesElements_FromSubMain()
    {
        var source = await GenerateAsync("web-site", SolutionTypes.JavaScript, "Main.bas");

        Assert.That(source, Does.Not.Contain("InitializeComponent"));
        Assert.That(source, Does.Contain("Sub Main()"));

        var form = DomDialect.Read(source);

        Assert.Multiple(() =>
        {
            Assert.That(form.Controls.Select(c => c.Id), Is.EqualTo(new[] { "heading", "button" }),
                "exactly the two elements GenerateWebSiteMain creates, in order");
            Assert.That(form.BuiltIn, Is.EqualTo("Main"),
                "the page is built in Sub Main, and a reader requiring a designer member finds nothing");
            Assert.That(form.IsRefused, Is.False);
        });

        var heading = form["heading"]!;
        Assert.Multiple(() =>
        {
            Assert.That(heading.TypeName, Is.EqualTo("h1"));
            Assert.That(heading.IsParented, Is.True, "doc.body.appendChild(heading)");
            Assert.That(heading.Properties["textContent"], Is.EqualTo("\"Hello from Recog\""));

            // ⚠ A real gap, asserted rather than papered over: the catalog has no row emitting <h1>,
            // so this element is recovered but not editable. Reporting that is the point — mapping
            // it to Label would rewrite the user's <h1> as a <label> on the next save.
            Assert.That(heading.CatalogKind, Is.Null);
            Assert.That(form.UnsupportedControls.Select(c => c.Id), Is.EqualTo(new[] { "heading" }));
        });

        var button = form["button"]!;
        Assert.Multiple(() =>
        {
            Assert.That(button.TypeName, Is.EqualTo("button"));
            Assert.That(button.CatalogKind, Is.EqualTo("Button"));
            Assert.That(button.IsParented, Is.True);
            Assert.That(button.Properties["textContent"], Is.EqualTo("\"Click me\""));
            Assert.That(button.Handlers, Has.Count.EqualTo(1));
            Assert.That(button.Handlers[0].Event, Is.EqualTo("click"));
            Assert.That(button.Handlers[0].IsInline, Is.True,
                "the web template wires an inline lambda, which is idiomatic, not a failure to find a Sub");
            Assert.That(button.Handlers[0].Handler, Is.Null);
        });
    }

    [Test]
    public async Task Dom_DoesNotReadAnAssignmentFromInsideAHandlerLambda()
    {
        // The template's AddHandler line contains `heading.textContent = "Clicked " & count …`
        // INSIDE a lambda. Reading it would make the page open showing its post-click caption.
        var source = await GenerateAsync("web-site", SolutionTypes.JavaScript, "Main.bas");
        Assert.That(source, Does.Contain("AddHandler counter.Changed"), "fixture sanity");

        var form = DomDialect.Read(source);

        Assert.That(form["heading"]!.Properties["textContent"], Is.EqualTo("\"Hello from Recog\""),
            "the designer value is the one assigned at construction, not the one a handler assigns later");
    }

    // ==================================================================
    // Fixture 3 — the VSIX template. The InitializeComponent shape.
    // ==================================================================

    /// <summary>
    /// ⛔ The VSIX template file carries unsubstituted <c>$safeprojectname$</c> placeholders, which
    /// VS replaces at instantiation. The fixture must substitute them too, or it is not testing the
    /// source a user would ever have.
    /// </summary>
    private static string ReadVsixMainForm()
    {
        var path = FindRepoFile("BasicLang.VisualStudio", "src", "BasicLang.VisualStudio",
            "Templates", "Projects", "WinFormsApp", "MainForm.bas");
        Assert.That(path, Is.Not.Null,
            "the VSIX WinFormsApp/MainForm.bas fixture is missing — it is the only InitializeComponent " +
            "shape in the repo, so losing it would leave that path untested");

        var source = File.ReadAllText(path!);
        Assert.That(source, Does.Contain("$safeprojectname$"), "fixture sanity: the placeholder is there");
        return source.Replace("$safeprojectname$", "VsixApp");
    }

    [Test]
    public void WinForms_RecoversTheVsixTemplatesControls_FromInitializeComponent()
    {
        var source = ReadVsixMainForm();
        Assert.That(source, Does.Contain("Private Sub InitializeComponent()"), "fixture sanity");

        var form = WinFormsDialect.Read(source);

        Assert.Multiple(() =>
        {
            Assert.That(form.ClassName, Is.EqualTo("MainForm"));
            Assert.That(form.BaseType, Is.EqualTo("Form"));
            Assert.That(form.BuiltIn, Is.EqualTo("InitializeComponent"),
                "the same dialect must read both shapes and report which one it found");
            Assert.That(form.Controls.Select(c => c.Id), Is.EqualTo(new[] { "lblMessage", "btnClick" }));
            Assert.That(form["lblMessage"]!.CatalogKind, Is.EqualTo("Label"));
            Assert.That(form["btnClick"]!.Handlers.Single().Handler, Is.EqualTo("btnClick_Click"),
                "a handler name containing an underscore is a normal identifier and must survive");
            Assert.That(form.FormProperties["Text"], Is.EqualTo("\"VsixApp\""),
                "the substituted placeholder, proving the fixture is the source a user would have");
            Assert.That(form.IsRefused, Is.False);
        });
    }

    [Test]
    public void WinForms_ReadsBothShapesIdentically()
    {
        // The single claim this task turns on: one dialect, two member names, same result.
        var vsix = WinFormsDialect.Read(ReadVsixMainForm());
        var template = WinFormsDialect.Read(TemplateShapedSource);

        Assert.That(template.Controls.Select(c => c.Id), Is.EqualTo(vsix.Controls.Select(c => c.Id)));
        Assert.That(template.Controls.Select(c => c.CatalogKind),
                    Is.EqualTo(vsix.Controls.Select(c => c.CatalogKind)));
        Assert.That(template.BuiltIn, Is.EqualTo("New"));
        Assert.That(vsix.BuiltIn, Is.EqualTo("InitializeComponent"));
    }

    // ==================================================================
    // Refusals — D9 Refused, never ignored
    // ==================================================================

    [Test]
    public void WinForms_Refuses_AHandlesClause()
    {
        // Handles is lexed but never parsed — Parser.cs contains zero TokenType.Handles — so a file
        // using it does not build. Importing it would show a designer view of a program that cannot run.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private btnClick As Button
                Private Sub btnClick_Click(sender As Object, e As EventArgs) Handles btnClick.Click
                End Sub
            End Class
            """);

        Assert.Multiple(() =>
        {
            Assert.That(form.IsRefused, Is.True, "a Handles clause must be REFUSED, not ignored");
            Assert.That(form.Refusals.Single().Code, Is.EqualTo("BL8001"));
            Assert.That(form.Refusals.Single().Line, Is.EqualTo(4));
            Assert.That(form.Refusals.Single().Message, Does.Contain("AddHandler"),
                "a refusal must say what to do instead");
        });
    }

    [Test]
    public void WinForms_Refuses_AWithBlockOverAControl()
    {
        // `.Prop = value` inside a With block is silently discarded: IRBuilder's assignment dispatch
        // has no arm for an implicit With member and no final else. The designer would show
        // properties the running program never sets.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private btnClick As Button
                Public Sub New()
                    btnClick = New Button()
                    With btnClick
                        .Text = "Click Me"
                    End With
                End Sub
            End Class
            """);

        Assert.Multiple(() =>
        {
            Assert.That(form.IsRefused, Is.True);
            Assert.That(form.Refusals.Single().Code, Is.EqualTo("BL8002"));
            Assert.That(form.Refusals.Single().Line, Is.EqualTo(6));
            Assert.That(form.Refusals.Single().Message, Does.Contain("silently discarded"));
        });
    }

    [Test]
    public void WinForms_DoesNotRefuse_AWithBlockOverSomethingThatIsNotAControl()
    {
        // Refusing every With would make the recognizer useless on ordinary code that happens to
        // sit in the same file.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Public Sub New()
                    With SomeUnrelatedThing
                        .Whatever = 1
                    End With
                End Sub
            End Class
            """);

        Assert.That(form.IsRefused, Is.False);
    }

    // ==================================================================
    // Tolerance and dialect selection
    // ==================================================================

    [Test]
    public void Recognizer_ToleratesASourceThatDoesNotFullyParse()
    {
        // The designer renders while the user is still typing in the code view, so a reader that
        // needed a clean parse would be unavailable exactly when it is wanted.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private btnClick As Button
                Public Sub New()
                    btnClick = New Button()
                    btnClick.Text = "Click Me"
                    If someCondition Then
            """);

        Assert.Multiple(() =>
        {
            Assert.That(form.Controls.Select(c => c.Id), Is.EqualTo(new[] { "btnClick" }));
            Assert.That(form["btnClick"]!.Properties["Text"], Is.EqualTo("\"Click Me\""));
        });
    }

    [Test]
    public void Recognizer_ToleratesAHalfTypedStringLiteral_RatherThanThrowing()
    {
        // ⛔ Lexer.Tokenize() THROWS on an unterminated string — and a half-typed string literal is
        // the single commonest state a file is in WHILE BEING EDITED, which is exactly when the
        // designer is asked to render it. The earlier tolerance test picked `If someCondition Then`,
        // which the lexer happily tokenizes, so it passed while this property did not hold.
        RecognizedForm form = null!;
        Assert.DoesNotThrow(() => form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private btnClick As Button
                Public Sub New()
                    btnClick = New Button()
                    btnClick.Text = "Click
            """));

        Assert.Multiple(() =>
        {
            Assert.That(form.UnreadableReason, Is.Not.Null,
                "the form must SAY it could not be read, not come back silently empty");
            Assert.That(form.Controls, Is.Empty);
        });
    }

    [Test]
    public void Dom_ToleratesAHalfTypedStringLiteral_RatherThanThrowing()
    {
        RecognizedForm form = null!;
        Assert.DoesNotThrow(() => form = DomDialect.Read("""
            Sub Main()
                Dim doc As Document = ::document
                Dim heading As Element = doc.createElement("h1
            """));

        Assert.That(form.UnreadableReason, Is.Not.Null);
    }

    [Test]
    public void WinForms_ReadsTheCombinedDeclareAndConstructForm()
    {
        // `Dim x As New Label()` carries no Assignment token, so the `<id> = New <Type>(` shape
        // never saw it and a form written this way opened completely EMPTY. The form is idiomatic
        // and this repo's own web template uses it (`Dim counter As New ClickCounter()`).
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private lblMessage As New Label()
                Public Sub New()
                    lblMessage.Text = "Hello"
                    Me.Controls.Add(lblMessage)
                End Sub
            End Class
            """);

        Assert.Multiple(() =>
        {
            Assert.That(form.Controls.Select(c => c.Id), Is.EqualTo(new[] { "lblMessage" }));
            Assert.That(form["lblMessage"]!.CatalogKind, Is.EqualTo("Label"));
            Assert.That(form["lblMessage"]!.ConstructionLine, Is.EqualTo(3));
            Assert.That(form["lblMessage"]!.Properties["Text"], Is.EqualTo("\"Hello\""));
            Assert.That(form["lblMessage"]!.IsParented, Is.True);
        });
    }

    [Test]
    public void WinForms_CountsAChildAddedToAContainer_AsParented()
    {
        // The catalog ships Panel and GroupBox as containers, so `pnlBox.Controls.Add(lblInner)` is
        // ordinary code. Matching only `Me.Controls.Add` gave every child of every container a
        // spurious "created but never added to the form" warning — design --check's most likely
        // false positive.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private pnlBox As Panel
                Private lblInner As Label
                Public Sub New()
                    pnlBox = New Panel()
                    lblInner = New Label()
                    pnlBox.Controls.Add(lblInner)
                    Me.Controls.Add(pnlBox)
                End Sub
            End Class
            """);

        Assert.Multiple(() =>
        {
            Assert.That(form["lblInner"]!.IsParented, Is.True, "added to a container, not to Me");
            Assert.That(form["pnlBox"]!.IsParented, Is.True);
        });
    }

    [Test]
    public void WinForms_DoesNotTreatAnOrdinaryFieldAsAControl()
    {
        // Accepting any declared identifier meant `Private db As Connection` + `db = New Connection()`
        // became a "control" with no catalog row, earning a BL8003 warning on an ordinary field —
        // and it disagreed with the declared-but-unconstructed pass, which was already catalog-only.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private db As Connection
                Private btnClick As Button
                Public Sub New()
                    db = New Connection()
                    btnClick = New Button()
                    Me.Controls.Add(btnClick)
                End Sub
            End Class
            """);

        Assert.That(form.Controls.Select(c => c.Id), Is.EqualTo(new[] { "btnClick" }),
            "only catalog types are controls, on BOTH the constructed and the declared-only path");
    }

    [Test]
    public void RawValue_StopsAtATrailingComment()
    {
        // Slicing to the end of the line swallowed the comment into the property value, and the
        // writer would then emit it back as part of the string. No shipped template puts a comment
        // on an assignment line, so no fixture caught it.
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private lblMessage As Label
                Public Sub New()
                    lblMessage = New Label()
                    lblMessage.Text = "Hi"   ' the greeting
                End Sub
            End Class
            """);

        Assert.That(form["lblMessage"]!.Properties["Text"], Is.EqualTo("\"Hi\""),
            "a trailing comment is not part of the value");
    }

    [Test]
    public void Dom_AppendChild_MarksTheArgument_NotTheReceiver()
    {
        // Marking every control named on the line meant `panel.appendChild(heading)` also marked
        // `panel` — so a container created and never attached to the document lost its orphan
        // warning, which is the case where that warning matters most.
        var form = DomDialect.Read("""
            Sub Main()
                Dim doc As Document = ::document
                Dim panel As Element = doc.createElement("div")
                Dim heading As Element = doc.createElement("h1")
                panel.appendChild(heading)
            End Sub
            """);

        Assert.Multiple(() =>
        {
            Assert.That(form["heading"]!.IsParented, Is.True, "it was the argument");
            Assert.That(form["panel"]!.IsParented, Is.False,
                "the receiver of appendChild is not thereby parented itself");
        });
    }

    [Test]
    public void WinForms_KeepsAFieldThatWasDeclaredButNeverConstructed()
    {
        var form = WinFormsDialect.Read("""
            Public Class MainForm
                Inherits Form
                Private lblOrphan As Label
                Public Sub New()
                End Sub
            End Class
            """);

        var orphan = form["lblOrphan"];
        Assert.Multiple(() =>
        {
            Assert.That(orphan, Is.Not.Null, "a declared control is the user's intent even unconstructed");
            Assert.That(orphan!.CatalogKind, Is.EqualTo("Label"));
            Assert.That(orphan.IsParented, Is.False);
            Assert.That(orphan.ConstructionLine, Is.Zero);
        });
    }

    [Test]
    public async Task DialectSelection_PicksTheRightReaderForEachTemplate()
    {
        var winforms = await GenerateAsync("winforms-app", SolutionTypes.DotNet, "Main.bas");
        var web = await GenerateAsync("web-site", SolutionTypes.JavaScript, "Main.bas");

        Assert.Multiple(() =>
        {
            Assert.That(WinFormsDialect.Looks(winforms), Is.True);
            Assert.That(DomDialect.Looks(winforms), Is.False);
            Assert.That(DomDialect.Looks(web), Is.True);
            Assert.That(WinFormsDialect.Looks(web), Is.False);
        });
    }

    // ==================================================================
    // SourceIndex
    // ==================================================================

    [Test]
    public void SourceIndex_RoundTripsPositionsAndOffsets()
    {
        var index = new SourceIndex("alpha\nbeta\ngamma");

        Assert.Multiple(() =>
        {
            Assert.That(index.LineCount, Is.EqualTo(3));
            Assert.That(index.OffsetOf(1, 1), Is.Zero);
            Assert.That(index.OffsetOf(2, 1), Is.EqualTo(6));
            Assert.That(index.OffsetOf(3, 3), Is.EqualTo(13));
            Assert.That(index.PositionOf(6), Is.EqualTo((2, 1)));
            Assert.That(index.PositionOf(13), Is.EqualTo((3, 3)));
            Assert.That(index.LineText(2), Is.EqualTo("beta"));
        });
    }

    [Test]
    public void SourceIndex_EndOfLine_StopsBeforeACarriageReturn()
    {
        // A span that swallowed the CR but not the LF would leave a lone LF behind and silently
        // change the file's line endings — the same class of damage as rewriting them wholesale.
        var index = new SourceIndex("alpha\r\nbeta\r\n");

        Assert.Multiple(() =>
        {
            Assert.That(index.LineText(1), Is.EqualTo("alpha"));
            Assert.That(index.LineText(2), Is.EqualTo("beta"));
            Assert.That(index.Slice(index.OffsetOf(1, 1), index.EndOfLine(1)), Is.EqualTo("alpha"));
        });
    }

    [Test]
    public void SourceIndex_ClampsRatherThanThrowing_ForAnOutOfRangePosition()
    {
        var index = new SourceIndex("alpha\nbeta");

        Assert.Multiple(() =>
        {
            Assert.That(index.OffsetOf(99, 1), Is.EqualTo(10));
            Assert.That(index.OffsetOf(0, 1), Is.Zero);
            Assert.That(index.OffsetOf(1, 999), Is.EqualTo(5), "clamps to the end of its own line");
            Assert.That(index.Slice(-5, 999), Is.EqualTo("alpha\nbeta"));
        });
    }

    /// <summary>
    /// The constructor-body shape, matching GenerateWinFormsMain, for the one test that has to
    /// compare two shapes side by side. Every other WinForms test reads the real generated source.
    /// </summary>
    private const string TemplateShapedSource = """
        Public Class MainForm
            Inherits Form

            Private lblMessage As Label
            Private btnClick As Button

            Public Sub New()
                Me.Text = "Recog"
                lblMessage = New Label()
                lblMessage.Text = "Hello"
                Me.Controls.Add(lblMessage)
                btnClick = New Button()
                btnClick.Text = "Click Me"
                AddHandler btnClick.Click, AddressOf OnButtonClick
                Me.Controls.Add(btnClick)
            End Sub
        End Class
        """;
}
